-- PostgreSQL schema for FoodWechatBotNew.
-- Apply with psql or any migration tool that preserves file order.

create table if not exists tenants (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    status text not null default 'active',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tenants_status_check check (status in ('active', 'disabled'))
);

create table if not exists users (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    display_name text not null default '',
    phone text,
    role text not null default 'member',
    status text not null default 'active',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint users_role_check check (role in ('owner', 'admin', 'member', 'operator')),
    constraint users_status_check check (status in ('active', 'disabled'))
);

create table if not exists user_identities (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    user_id bigint references users(id),
    provider text not null,
    external_id text not null,
    open_kfid text,
    chat_id text,
    raw_profile jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (tenant_id, provider, external_id)
);

create table if not exists api_clients (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    name text not null,
    token_hash text not null,
    scopes text[] not null default '{}'::text[],
    status text not null default 'active',
    created_at timestamptz not null default now(),
    rotated_at timestamptz,
    constraint api_clients_status_check check (status in ('active', 'disabled'))
);

create table if not exists stores (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    code text,
    name text not null,
    region text,
    address text,
    status text not null default 'active',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, name),
    constraint stores_status_check check (status in ('active', 'disabled'))
);

create table if not exists store_aliases (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    store_id bigint not null references stores(id) on delete cascade,
    alias text not null,
    source text not null default 'manual',
    created_at timestamptz not null default now(),
    unique (tenant_id, alias)
);

create table if not exists user_store_roles (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    user_id bigint not null references users(id),
    store_id bigint not null references stores(id),
    role text not null default 'operator',
    is_default boolean not null default false,
    created_at timestamptz not null default now(),
    unique (tenant_id, user_id, store_id)
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    code text,
    name text not null,
    spec text,
    unit text,
    category text,
    status text not null default 'active',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, code),
    constraint products_status_check check (status in ('active', 'disabled'))
);

create table if not exists product_aliases (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    product_id bigint not null references products(id) on delete cascade,
    alias text not null,
    source text not null default 'manual',
    created_at timestamptz not null default now(),
    unique (tenant_id, alias)
);

create table if not exists conversations (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    user_id bigint references users(id),
    identity_id bigint references user_identities(id),
    channel text not null,
    external_session_key text,
    mode text not null default 'interview',
    store_id bigint references stores(id),
    state jsonb not null default '{}'::jsonb,
    last_message_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, channel, external_session_key),
    constraint conversations_mode_check check (mode in ('interview', 'order', 'receipt'))
);

create table if not exists conversation_messages (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    conversation_id bigint not null references conversations(id) on delete cascade,
    sender_user_id bigint references users(id),
    role text not null,
    message_type text not null default 'text',
    content text not null default '',
    raw_ref text,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint conversation_messages_role_check check (role in ('user', 'assistant', 'system'))
);

create table if not exists source_messages (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    conversation_id bigint references conversations(id),
    message_id bigint references conversation_messages(id),
    channel text not null,
    raw_ref text not null,
    external_msg_id text,
    source_type text not null,
    file_name text,
    mime_type text,
    media_id text,
    content text,
    raw_payload jsonb not null default '{}'::jsonb,
    received_at timestamptz not null default now(),
    unique (tenant_id, raw_ref)
);

create table if not exists import_batches (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    source_message_id bigint references source_messages(id),
    created_by bigint references users(id),
    source text not null,
    raw_ref text,
    file_name text,
    file_hash text,
    status text not null default 'parsed',
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    store_id bigint references stores(id),
    store_name_snapshot text,
    conversation_id bigint references conversations(id),
    source_message_id bigint references source_messages(id),
    import_batch_id bigint references import_batches(id),
    kind text not null,
    source text not null,
    status text not null default 'new',
    confirmed boolean not null default false,
    confirmed_at timestamptz,
    fetched_at timestamptz,
    cancelled_at timestamptz,
    order_no text,
    orderer_name text,
    orderer_user_id bigint references users(id),
    order_date date not null,
    deliver_date date,
    change_type text,
    parent_order_id bigint references orders(id),
    raw_text text,
    raw_ref text,
    raw_payload jsonb not null default '{}'::jsonb,
    legacy_source text,
    legacy_id bigint,
    created_by bigint references users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (tenant_id, legacy_source, legacy_id),
    constraint orders_kind_check check (kind in ('base', 'patch')),
    constraint orders_source_check check (source in ('excel', 'photo', 'text', 'api')),
    constraint orders_status_check check (status in ('new', 'fetched', 'cancelled')),
    constraint orders_change_type_check check (change_type is null or change_type in ('add', 'modify'))
);

create table if not exists order_items (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    order_id bigint not null references orders(id) on delete cascade,
    product_id bigint references products(id),
    line_no integer not null default 1,
    product_code text,
    product_name text not null,
    spec text,
    unit text,
    qty numeric(14, 3) not null,
    price numeric(14, 4),
    category text,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists order_fetch_events (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    order_id bigint not null references orders(id),
    api_client_id bigint references api_clients(id),
    action text not null default 'mark_fetched',
    request_id text,
    created_at timestamptz not null default now()
);

create table if not exists production_receipts (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    conversation_id bigint references conversations(id),
    source_message_id bigint references source_messages(id),
    import_batch_id bigint references import_batches(id),
    receipt_no text,
    receipt_date date not null,
    status text not null default 'confirmed',
    source text not null default 'photo',
    raw_ref text,
    raw_payload jsonb not null default '{}'::jsonb,
    legacy_source text,
    legacy_id bigint,
    created_by bigint references users(id),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    cancelled_at timestamptz,
    unique (tenant_id, legacy_source, legacy_id),
    constraint production_receipts_status_check check (status in ('confirmed', 'cancelled')),
    constraint production_receipts_source_check check (source in ('photo', 'api', 'manual'))
);

create table if not exists production_receipt_items (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    receipt_id bigint not null references production_receipts(id) on delete cascade,
    product_id bigint references products(id),
    line_no integer not null default 1,
    product_code text,
    product_name text not null,
    spec text,
    unit text,
    qty numeric(14, 3) not null,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists channel_cursors (
    id bigint generated by default as identity primary key,
    tenant_id bigint not null references tenants(id),
    channel text not null,
    cursor_key text not null,
    cursor_value text not null default '',
    updated_at timestamptz not null default now(),
    unique (tenant_id, channel, cursor_key)
);

create index if not exists idx_users_tenant_status on users (tenant_id, status);
create index if not exists idx_user_identities_user_id on user_identities (user_id);
create index if not exists idx_stores_tenant_status on stores (tenant_id, status);
create index if not exists idx_products_tenant_name on products (tenant_id, name);
create index if not exists idx_conversations_lookup on conversations (tenant_id, channel, external_session_key);
create index if not exists idx_conversation_messages_conversation on conversation_messages (conversation_id, id);
create index if not exists idx_source_messages_external on source_messages (tenant_id, channel, external_msg_id);
create index if not exists idx_orders_tenant_status_date on orders (tenant_id, status, order_date, id);
create index if not exists idx_orders_tenant_store_date on orders (tenant_id, store_id, order_date, id);
create index if not exists idx_orders_raw_ref on orders (tenant_id, raw_ref);
create index if not exists idx_orders_confirmed_date on orders (tenant_id, order_date, id) where confirmed = true and status <> 'cancelled';
create index if not exists idx_order_items_order_id on order_items (order_id, line_no, id);
create index if not exists idx_order_fetch_events_order on order_fetch_events (tenant_id, order_id, created_at);
create index if not exists idx_receipts_tenant_date_status on production_receipts (tenant_id, receipt_date, status, id);
create index if not exists idx_receipt_items_receipt_id on production_receipt_items (receipt_id, line_no, id);
